import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.content_bg}>
      <Head>
        <title>Sea 2 Sky info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className={styles.title}>
          Sea 2 Sky
        </h1>

        <p className={styles.description}>
          Every thing you need to know to plan your weekend getaway in the Sea 2 Sky corridor!
        </p>
        <main className={styles.main}>
          <a href="/Pembertion" className={styles.card_1}>
            <h2>Pemberton &rarr;</h2>
            <p>Adventure begins here! Your gateway to unlimited wildness</p>
          </a>

          <a href="/Whistler" className={styles.card_2}>
            <h2>Whistler&rarr;</h2>
            <p>World class resort town, ready to welcome you year round</p>
          </a>

          <a
            href="Squamish"
            className={styles.card_3}
          >
            <h2>Squamish&rarr;</h2>
            <p>Canadas best spot for biking, climbing and windsurfing</p>
          </a>

          <a
            href="/about"
            className={styles.card_4}
          >
            <h2>About the Author &rarr;</h2>
         
          </a>
      <p className={styles.paragraph}>Highway 99 or the Sea to Sky corridor is a world class outdoor rectation hotspot. With a 
        wide array of winter and summer actitives there is something to do year round. The highway links
        three towns each with their own unquie offerings. Use this site to get to know each town and plan your next trip.
      
      </p>
      <img
        src="SeaToSky_HighwayMap.jpg"
        alt="Map of the sea to sky highway"
        className={styles.image}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
