import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.content_bg}>
      <Head>
        <title>Sea 2 Sky info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Sea 2 Sky
        </h1>

        <p className={styles.description}>
          Every thing you need to know to plan your weekend getaway in the Sea 2 Sky corridor!
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Pemberton &rarr;</h2>
            <p>Adventure begins here! Your gateway to unlimited wildness</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Whistler</h2>
            <p>World class resort town, ready to welcome you year round</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Squamish&rarr;</h2>
            <p>Canadas best spot for biking, climbing and windsurfing</p>
          </a>

          <a
            href="/about"
            className={styles.card}
          >
            <h2>About the Author &rarr;</h2>
         
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
